### ISSUE TITLE
新版社区网站

### ISSUE THREAD

**Issue by tvvocold** [FZUG/ggmm#1]
Hi @FZUG , 

我在考虑是否可以用Github的Page做新版社区首页?这样大家都可以贡献/Push? http://1.fdzh.org  or http://demo.fdzh.org ?  或者你发现/有更好的Page?

**Comment by tvvocold** [comment]
https://github.com/FZUG/demofdzh.github.com

**Comment by tvvocold** [comment]
@FZUG/tier1 @FZUG/owners

**Comment by tonghuix** [comment]
我覺得值得一試，不過維護成本可能會略高。不過試試總歸是好的。FOSSASIA的網頁就是放在Github上的，然後大家誰都可以維護，特別是FOSSASIA參加GSoC以後，收錄mentor的各種idear是很方便的。

不過這個前提是有一個強力領導者，善於和懂得如何維護，看似簡單，其實還是挺複雜的一件事呢。

列在此，請各位參考：
https://github.com/fossasia/fossasia15
https://github.com/fossasia/labs.fossasia.org
https://github.com/fossasia/fossasia-communities
https://github.com/fossasia/api.fossasia.net
https://github.com/fossasia/fossasia.github.io

**Comment by tvvocold** [comment]
恩，这个也不错。
https://github.com/fex-team/fex-team.github.io

**Comment by alick** [comment]
问题是：
1. 之前有了一个结论：没有“官方”中文社区网站，每个人都可以建自己的。
2. 如果再建一个，上面放什么内容？展示什么东西？

**Comment by alick** [comment]
PS: 这个 issue 出现在 fzh-meeting-loger 项目下，不合适吧。

**Comment by tvvocold** [comment]
@alick9188 
不是再建一个，做好之后即可使用www.fdzh.org的CNAME。因为我在管理fdzh.org时候感到还是人多力量大，所以想把www.fdzh.org转型为社区共同建设的主页。这样大家都可以push自己的文章上去。
内容的话类似fex-team.github.io, 展示社区的新闻或其他相关信息。

**Comment by tonghuix** [comment]
这。。。说句打击你的话，以现在Fedora社区的现状，没有那么大的UGC能力，也没有足够的贡献能力。不要想的太理想化。

至于社区首页放什么内容，其实都在Fedora Wiki上有所体现了，那个首页就很好，直接把域名做个转发也不错。如果想要美化一下，显得正规一点也倒不是不可以，只是这个真的工作量挺大。我评估大概中等工作量，大概是10人日左右，搞定以后每个月还要投入2人日来维护，成本还是挺高的。在现有社区活跃度不高，社区贡献比较少的情况下，最大的可能还是一个人完成，不要寄希望于大家贡献内容。

最后说一个我的想法，我还是挺支持有个社区主页的，只是以个人之力完成，其他的真心别考虑大家UGC了。

**Comment by tvvocold** [comment]
OK
