### ISSUE TITLE
项目（工具）名称

### ISSUE THREAD

**Issue by alick** [FZUG/ggmm#2]
现有的名称 fzh-meeting-loger 里包含拼写错误 loger => logger. 此外，我觉得它本身也不太合适，因为它不是记录会议纪要的，而是把已记录的会议纪要转换成邮件格式的。

我有个想法，可以叫 ggmm，意为 GGMM Generates Minutes Mail。
大家怎么看？有没别的好想法？

**Comment by tvvocold** [comment]
+1
PS: 
fedora-infra组下也有类似IFTTT的自动提醒，可以满足在IRC或者Mail环境下的Copr, meetings等自动提醒，另外，自动发送会议纪要到邮件列表 的Feature也貌似在开发中，大家可以尝试下。
https://apps.fedoraproject.org/notifications
https://github.com/fedora-infra/fedmsg

**Comment by Endle** [comment]
@alick9188 commented on [2015年3月13日 GMT+8下午6:37](https://github.com/FZUG/fzh-meeting-loger/issues/2#issue-61033565):

> 我有个想法，可以叫 ggmm，意为 GGMM Generates Minutes Mail。
> 大家怎么看？有没别的好想法？

Agree
你应该有权限修改吧

**Comment by alick** [comment]
嗯，那我改了。我们应该都有权限改的。

2015-03-13 19:07 GMT+08:00 Zhenbo Li notifications@github.com:

**Comment by alick** [comment]
renamed
