### ISSUE TITLE
自动发送会议纪要到邮件列表 

### ISSUE THREAD

**Issue by tvvocold** [FZUG/ggmm#3]
Hi @FZUG/tier1 ,

Fedora App [1] 提供的自动发邮件 (每当 #fedora-zh 里有人 #endmeeting 时会自动发送 zotbot 生成的会议纪要） 到 指定邮箱 已测试成功[2]。

能否启用（我开启转发到邮件列表）?

[1] https://apps.fedoraproject.org/notifications
[2] http://p.fdzh.org/paste/wzy0qqb3

Cheers,
Ray

**Comment by alick** [comment]
赞，很不错的feature。

是说可以配置发送邮件到列表？这个配置是在 fedora infra 做的吗？需要列表做什么事情？例如是不是需要把发信人加入列表？

**Comment by alick** [comment]
如果启用的话，是不是和 ggmm 小程序的功能重叠了？

我个人其实期望 ggmm 能够更智能一点：比如解析会议的topic总结出会议的主要内容，自动计算下次会议的日期，等等。这些功能也许无法被 Fedora Notifications 取代？

**Comment by tvvocold** [comment]
@alick9188 

恩，以后会议结束就不需要找人来发会议纪要了。Fedora Notifications 会在 #fedora-zh 有人 #endmeeting 时自动发送 zotbot 生成的会议纪要到我的邮箱。接下来我只需要在 Gmail 添加一个自动转发到邮件列表的过滤器即可。（或者把邮件列表邮箱加入到 APP 的通知邮箱中，这样的话需要把发信 Bot 即 notifications@fedoraproject.org 加入 fedora-zh 的邮件订阅组吧，但是 Bot 的访问权不在我们手中）

PS：其实平时邮件头部会议的 topic 在邮件内容中也有，没必要人工来写。
另外，[IFTTT](http://www.ifttt.com) 可以实现自动发提醒邮件组参加会议的功能。这样会议前后都是 Bot 了.

**Comment by sztsian** [comment]
> 恩，以后会议结束就不需要找人来发会议纪要了。Fedora Notifications 会在 #fedora-zh 有人 #endmeeting 时自动发送 zotbot 生成的会议纪要到我的邮箱。接下来我只需要在 Gmail 添加一个自动转发到邮件列表的过滤器即可。（或者把邮件列表邮箱加入到 APP 的通知邮箱中，这样的话需要把发信 Bot 即 notifications@fedoraproject.org 加入 fedora-zh 的邮件订阅组吧，但是 Bot 的访问权不在我们手中）

我反对让bot（notifications@fp.o）进入fedora-zh的做法。个人认为让bot进入一个列表有失妥当。
我更倾向于，谁有linux服务器且可以贡献一下做一个.procmail？这样让procmail去运行ggmm来生成邮件，并发送到列表，会更完美些。

> PS：其实平时邮件头部会议的 topic 在邮件内容中也有，没必要人工来写。
> 另外，[IFTTT](http://www.ifttt.com) 可以实现自动发提醒邮件组参加会议的功能。这样会议前后都是 Bot 了.

现在会议前的reminder是fedcal自动发的。

**Comment by tvvocold** [comment]
@sztsian 
事实上，官方也是用该 Bot 发邮件列表的[1]。
[1] https://lists.fedoraproject.org/pipermail/meetingminutes/2015-March/thread.html
 https://lists.fedoraproject.org/pipermail/meetingminutes/2015-March/001767.html

**Comment by sztsian** [comment]
@tvvocold 
这些邮件我此前已经留心到了。但meetingminutes列表的主要作用就是归档来自各个会议的纪要，其归档意义大于交流意义。而我认为chinese列表主要的作用在于交流，因此会议纪要头部的“下次会议时间”等内容是不可或缺的。这是我不太赞同直接让notif..@fp.o发送到chinese列表的原因。
